version: '3'
services:
  mydb:
    build:
      context: ./mydb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mydb/store:/var/lib/mysql
    networks:
      - network
  neodb:
    build:
      context: ./neodb
      dockerfile: Dockerfile
    ports:
      - 7687:7687
    volumes:
      - ./neodb/data:/var/lib/neo4j/data
      - ./neodb/logs:/var/lib/neo4j/logs
      - ./neodb/conf:/var/lib/neo4j/conf
    networks:
      - network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mydb
      - neodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Todwnl@7706

      SPRING_NEO4J_URI: bolt://neodb:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: root1234
    networks:
      - network

networks:
  network: