version: '3'
services:
  mydb:
    build:
      context: ./mydb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mydb/mysql-config/:/etc/mysql/conf.d  # MySQL 설정 파일을 로컬에서 관리
      - ./mydb/init.sql/:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  neodb:
    build:
      context: ./neodb
      dockerfile: Dockerfile
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    volumes:
      - ./neodb/data:/var/lib/neo4j/data
      - ./neodb/logs:/var/lib/neo4j/logs
      - ./neodb/conf:/var/lib/neo4j/conf
    networks:
      - network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mydb
      - neodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_NEO4J_URI: bolt://neodb:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: root1234
    networks:
      - network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - network
networks:
  network: