spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: # ??? ????? ??? ? ???? ????? ?? ??
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # create, update, create-drop, validate ? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


